/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mlSidebar: [
    {
      type: 'doc',
      id: 'intro'
    },
    {
      type: 'category',
      label: 'Machine Learning',
      link: {
        type: 'generated-index',
        title: '🚀Machine Learning',
        description: "All the topics associated with Machine Learning.",
        slug: 'ml/intro',
        keywords: ['basics', 'machine learning'],

      },
      items: [
        {
          type: 'category',
          label: 'Mathematics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/mathematics'
            }
          ]
        },
        {
          type: 'category',
          label: 'Interview',
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/interview'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'MLOps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'MLOps'
        }
      ]
    },
    {
      type: 'category',
      label: 'System Design',
      link: {
        type: 'generated-index',
        title: '🗺 System Design',
        description: "Everything related to System Design.",
        slug: 'system-design/what-is-system-design',
        keywords: ['system design', 'design'],

      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'system-design'
        }
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
