/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mlSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🙋‍♂️ Introduction'
    },
    {
      type: 'category',
      label: '🤖 Machine Learning',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '🤖 Machine Learning',
        description: "Want to learn ML for free? Checkout out these 👇 resourcse",
        slug: '/ml',
        keywords: ['machine learning', 'ML', 'data science'],

      },
      items: [
        {
          type: 'category',
          label: '🔢 Mathematics',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Mathematics',
            description: '👇 Mathematics resources necessary to get started with Machine learning.'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/mathematics',

            }
          ]
        },
        {
          type: 'category',
          label: '⌛ Algorithms',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Algorithms',
            description: '👇 Some important Machine learning algorithms.'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/algorithms'
            }
          ]
        },
        {
          type: 'category',
          label: '🔡 Natural Language Processing',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Natural Language Processing',
            description: '👇 NLP notes to get started with natural language processing.'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/nlp'
            }
          ]
        },
        {
          type: 'category',
          label: '📷 Computer Vision',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Computer Vision',
            description: '👇 Computer vision notes and resources'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'ML/cv'
            }
          ]
        },

      ]
    },

    {
      type: 'category',
      label: '🦾 Machine Learning Operations (MLOps)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '🦾 Machine Learning Operations (MLOps)',
        description: "A collection of resources on MLOps.",
        slug: '/mlops',
        keywords: ['mlops', 'machine learning', 'kubernetes', 'docker'],

      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MLOps'
        }
      ]
    },
    // {
    //   type: 'category',
    //   label: 'MLOps',
    //   collapsed: false,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'MLOps'
    //     }
    //   ]
    // },
    {
      type: 'category',
      label: '💻 System Design',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '💻 System Design',
        description: "Everything related to System Design.",
        slug: '/system-design/what-is-system-design',
        keywords: ['system design', 'design'],

      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'system-design'
        }
      ]
    },
    {
      type: 'category',
      label: '🧠 Interview',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '🧠 Interview',
        description: 'Have an interview? Fear not, Checkout these awesome interview resources 👇',
        slug: '/interview',
        keywords: ['interview', 'leetcode', 'machine learning']
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'interview'
        }
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
